### ISSUE TITLE
KtxActivityLifecycleCallbacks

### ISSUE THREAD

**Issue by android-1995** [hegaojian/MvvmHelper#13]
KtxActivityLifecycleCallbacks的onActivityDestroyed调用了finishActivity，会导致切换暗黑模式的时候Activity被finish

**Comment by hegaojian** [comment]
我待会发布一版吧，在onActivityDestroyed方法里，只移除栈，不调用finishActivity

**Comment by android-1995** [comment]
加油 坤坤

**Comment by hegaojian** [comment]
试试 最新版 1.1.0
