### ISSUE TITLE
BaseVmActivity 生命周期执行顺序问题

### ISSUE THREAD

**Issue by bingdu0** [hegaojian/MvvmHelper#16]
```
BaseVmActivity  中的initStatusView(savedInstanceState: Bundle?) 方法，
  findViewById<FrameLayout>(R.id.baseContentView).post {
            initView(savedInstanceState)
}

这个地方 会在oncreate onresume 执行完成之后才会执行到initView 方法。如果在onresume中做一些逻辑操作，会造成页面不更新。
```

**Comment by hegaojian** [comment]
写这延迟是因为用了LoadSir 他注册完View后会自动显示默认的Callback，如果不加延迟的话，在initview中执行loading显示，它注册完成后会自动覆盖变成success界面，你再onresume做的是 Ui逻辑操作吗，按理来说这时候已经能拿到view了

**Comment by bingdu0** [comment]
对，请求了一下网络数据，但是请求数据返回了才执行initView  ，我现在把post 去掉了 ，直接调用initViewinitView(savedInstanceState)没发现问题啊。还有一个问题就是 viewmodel 怎么传值啊？

**Comment by bingdu0** [comment]
> 写这延迟是因为用了LoadSir 他注册完View后会自动显示默认的Callback，如果不加延迟的话，在initview中执行loading显示，它注册完成后会自动覆盖变成success界面，你再onresume做的是 Ui逻辑操作吗，按理来说这时候已经能拿到view了

对，请求了一下网络数据，但是请求数据返回了才执行initView ，我现在把post 去掉了 ，直接调用initViewinitView(savedInstanceState)没发现问题啊。还有一个问题就是 viewmodel 怎么传值啊？

**Comment by hegaojian** [comment]
你取消延迟后，如果请求时，loading类型为 Loading_Xml 就会有不出现loading的问题， viewmodel传值，不太理解你的意思，具体你是想传值给谁

**Comment by bingdu0** [comment]
> 你取消延迟后，如果请求时，loading类型为 Loading_Xml 就会有不出现loading的问题， viewmodel传值，不太理解你的意思，具体你是想传值给谁
post 的那个问题我再看看。viewmodel 的构造中传一个Repository。
