### ISSUE TITLE
能否维护一下rxhttp的新版本

### ISSUE THREAD

**Issue by bingdu0** [hegaojian/MvvmHelper#17]
作者你好，能否维护一下rxhttp 的新版本，新版本适配了flow，能否适配一下。另外rxlife-coroutine 这个自动管理协程生命周期的库 也已经废弃掉了，希望作者能维护一下。

**Comment by hegaojian** [comment]
近期会更新一版的，升级 rxhttp的版本和去掉 rxlife,同时兼容新的rxhttp写法

**Comment by hegaojian** [comment]
已升级到rxHttp最新版本

**Comment by hegaojian** [comment]
这个rxHttp版本改动有点大，使用时需要稍微修改一点东西，
1.Rxhttp初始化问题
解决--> RxHttpPlugins.init() 使用RxHttpPlugins初始化
2.使用RxHttp调用请求返回的 IWait需修改为Await
其他的具体可查看demo

**Comment by bingdu0** [comment]
> 这个rxHttp版本改动有点大，使用时需要稍微修改一点东西， 1.Rxhttp初始化问题 解决--> RxHttpPlugins.init() 使用RxHttpPlugins初始化 2.使用RxHttp调用请求返回的 IWait需修改为Await 其他的具体可查看demo

好的，多谢
