### ISSUE TITLE
添加Navigation后，报错反射异常

### ISSUE THREAD

**Issue by wangsong1991** [hegaojian/MvvmHelper#21]
![1638344168(1)](https://user-images.githubusercontent.com/9698820/144191605-f8b47589-9d96-4b49-a2ff-61c6ec00e93c.jpg)
![1638344078(1)](https://user-images.githubusercontent.com/9698820/144191616-808500e5-7566-4105-b70b-9d7faaa4b097.jpg)

**Comment by wangsong1991** [comment]
这是什么原因呢？反复查看代码也没有问题，代码指向base
![1638344698(1)](https://user-images.githubusercontent.com/9698820/144192608-bf2d48e7-bef2-4f29-aaee-6bba5d749a56.jpg)

**Comment by hegaojian** [comment]
这个控件被反射后会出现这种bug,目前发现还有<fragment/> 控件也会有这问题，你可以将这个界面的Activity 单独不用继承反射基类， 继承普通的 BaseVmActivity ，目前这个问题，暂时没有找到好的解决办法

**Comment by hegaojian** [comment]
已更新到 1.1.4 ，解决了这个bug了

**Comment by PiterPeng** [comment]
nb
