### ISSUE TITLE
想问下，这是个项目还是个架构模板还是工具插件，跑起来之后不知道怎样登录，代码结构也看不懂😢

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [hegaojian/MvvmHelper#22]

**Comment by SaltedFish-Extreme** [comment]
还有这个启动图实在是太那个了，下午刚跑起来就被我爸看着了，太尴尬了🤔

**Comment by hegaojian** [comment]
demo里面有个登录示例的，你可以看看

**Comment by hegaojian** [comment]
> 还有这个启动图实在是太那个了，下午刚跑起来就被我爸看着了，太尴尬了🤔

没事，问题不大，只要你不尴尬，尴尬的就是你爸

**Comment by hegaojian** [comment]
这个项目是框架模版呢

**Comment by SaltedFish-Extreme** [comment]
> 这个项目是框架模版呢

😂这样，怪不得登录不上，玩安卓api登录用的用户名和密码，这个账号输入框只能输手机号，感觉这个注释有点少，mvvm代码的结构跟我之前用郭霖的第一行代码的项目也有挺大的差别，另外感觉略功能有点简陋，我目前在看轮子哥的安卓技术中台，那个可以借鉴的东西挺多的，我也准备做一个玩安卓app，在参照你做的和另外几个老哥的UI控件之类的😉

**Comment by hegaojian** [comment]
> 😂这样，怪不得登录不上，玩安卓api登录用的用户名和密码，这个账号输入框只能输手机号，感觉这个注释有点少，mvvm代码的结构跟我之前用郭霖的第一行代码的项目也有挺大的差别，另外感觉略功能有点简陋，我目前在看轮子哥的安卓技术中台，那个可以借鉴的东西挺多的，我也准备做一个玩安卓app，在参照你做的和另外几个老哥的UI控件之类的😉

这个项目框架是给自己平时用的，按照自己喜欢的写法去搭建，demo只是简单的介绍一下框架大概的用法，所以功能很简陋

**Comment by hegaojian** [comment]
> 😂这样，怪不得登录不上，玩安卓api登录用的用户名和密码，这个账号输入框只能输手机号，感觉这个注释有点少，mvvm代码的结构跟我之前用郭霖的第一行代码的项目也有挺大的差别，另外感觉略功能有点简陋，我目前在看轮子哥的安卓技术中台，那个可以借鉴的东西挺多的，我也准备做一个玩安卓app，在参照你做的和另外几个老哥的UI控件之类的😉

这个项目框架是给自己平时用的，按照自己喜欢的写法去搭建，demo只是简单的介绍一下框架大概的用法，所以功能很简陋

**Comment by SaltedFish-Extreme** [comment]
> > 😂这样，怪不得登录不上，玩安卓api登录用的用户名和密码，这个账号输入框只能输手机号，感觉这个注释有点少，mvvm代码的结构跟我之前用郭霖的第一行代码的项目也有挺大的差别，另外感觉略功能有点简陋，我目前在看轮子哥的安卓技术中台，那个可以借鉴的东西挺多的，我也准备做一个玩安卓app，在参照你做的和另外几个老哥的UI控件之类的😉
> 
> 这个项目框架是给自己平时用的，按照自己喜欢的写法去搭建，demo只是简单的介绍一下框架大概的用法，所以功能很简陋

这样啊，明白了😉
