### ISSUE TITLE
想请教下 如何给不同的界面设置空数据的UI样式

### ISSUE THREAD

**Issue by jalen2024** [hegaojian/MvvmHelper#26]
您好，想请教下 如何给不同的界面设置空数据的UI样式，同时新增空数据里更多按钮的点击事件处理。

**Comment by hegaojian** [comment]
你可以单独给某个页面自定义一个 LoadSir,添加一个空布局的CallBack。
LoadSir这个库默认CallBack 是整个页面点击就触发回调事件，如果想单独设置一个按钮的点击事件的话 需要改造一下他的库，或者看下 LoadSir的文档

**Comment by hegaojian** [comment]
1.1.7版本已经支持 不同的界面传入不同的 空、错误、加载 布局UI样式 @jalen2024

**Comment by NicodeLee** [comment]
@hegaojian 我想问问错误后重试在哪里，没有onRetryClickListener

**Comment by hegaojian** [comment]
在Activity/Fragment里面重写 ``onLoadRetry``方法，所有不同状态布局点击重试都会触发该方法 @NicodeLee

**Comment by NicodeLee** [comment]
好的，感谢鸡哥的解答
