### ISSUE TITLE
后台启动Activity，toolbar不显示

### ISSUE THREAD

**Issue by yangxiaoge** [hegaojian/MvvmHelper#27]
例如`SplashActivity`，如果设置显示`showToolBar=true`, 正常打开是显示toolbar的。但是如果把设备锁屏，然后运行AS启动应用，等初始化完成后，解锁设置，会发现toolbar不显示。

**Comment by hegaojian** [comment]
复现不出来，我测试了一下，锁屏，运行项目，解锁后，标题栏还是存在显示的

**Comment by yangxiaoge** [comment]
> 复现不出来，我测试了一下，锁屏，运行项目，解锁后，标题栏还是存在显示的

![image](https://user-images.githubusercontent.com/12471093/194681447-2bb0ac7d-7ef0-425f-8cfe-d2fcb9d3686b.png)
如上图，改动两个地方，然后手机锁定屏幕，as直接run demo，toolbar不显示。如果解锁屏幕，反之。

**Comment by hegaojian** [comment]
你是什么设备，我这个设备一直OK

**Comment by yangxiaoge** [comment]
> 你是什么设备，我这个设备一直OK

![image](https://user-images.githubusercontent.com/12471093/194683052-93f542d8-b8cd-4342-8012-6710041c0849.png)
Android10的，PDA设备比较冷门

**Comment by yangxiaoge** [comment]
> 你是什么设备，我这个设备一直OK

我换了一台设备，小米6，Android9，也是同样问题

**Comment by hegaojian** [comment]
是有问题，我换了一个手机复现出来了，不过找不到具体是什么原理导致的，通过断点查看到 toolbar确实是已经添加进去了的，我后面 手动让toolbar 显示也没有效果。先不管了，这个情景下的bug不影响用户的使用
