### ISSUE TITLE
最新版本，好多第三方库拉不下来。鸡哥，这些要怎么解决？

### ISSUE THREAD

**Issue by kanfRUI** [hegaojian/MvvmHelper#30]
Could not find com.github.zhaokaiqiang.klog:library:1.6.0.
Could not find com.effective.android:anchors:1.1.1.
Could not find com.gyf.immersionbar:immersionbar:3.0.0.
Could not find com.gyf.immersionbar:immersionbar-ktx:3.0.0.
Could not find com.scwang.smart:refresh-layout-kernel:2.0.1
Could not find com.scwang.smart:refresh-header-classics:2.0.1.
Could not find com.noober.background:core:1.6.5.

**Comment by hegaojian** [comment]
```
maven { url 'https://maven.aliyun.com/repository/central' } 
```
加上这个试试

**Comment by kanfRUI** [comment]
好像可以了，谢了
