### ISSUE TITLE
BaseDBActivity\BaseDBFragment是否多余？

### ISSUE THREAD

**Issue by wkbin** [hegaojian/MvvmHelper#32]
ViewDataBinding 实际上已经实现了ViewBinding接口，因此使用DataBinding，传入BaseVBActivity没有什么问题，可以自动推导出他是databinding

**Comment by hegaojian** [comment]
你说的是对的，亲测了一下，确实没什么问题，当时设计时按照固有思维，直接写了2套，现在来看的话duck不必。感谢你的建议
