### ISSUE TITLE
How to use AppViewModel as JetpackMvvm project

### ISSUE THREAD

**Issue by Bugzer0** [hegaojian/MvvmHelper#33]
I want to use global variable, for example i use AppViewModel in JetpackMvvm project
`class AppViewModel : BaseViewModel() {
       var userInfo = UnPeekLiveData.Builder<UserInfo>().setAllowNullValue(true).create()
}
`
in MvvmHelper, is there any substitute?
thanks for awesome lib

**Comment by hegaojian** [comment]
其实AppViewModel就相当于一个全局单例对象 ，在MvvmHelper中，你可以不使用AppViewModel这种方式，可以将其写在单例类中
比如
```
object GlobalObject{
 var userInfo = UnPeekLiveData.Builder<UserInfo>().setAllowNullValue(true).create() 
}
```

**Comment by hegaojian** [comment]
In fact, AppViewModel is equivalent to a global singleton object, in MvvmHelper, you can write it in the singleton class
For example:
```
object GlobalObject{
 var userInfo = UnPeekLiveData.Builder<UserInfo>().setAllowNullValue(true).create() 
}
```
