### ISSUE TITLE
冒昧的请问一下，这框架有在更新维护吗？

### ISSUE THREAD

**Issue by benxiongbuben** [hegaojian/MvvmHelper#34]
框架目前还是比较好用的，但是请问一下是否有做计划对里面的一些框架进行更新操作？比如更新以下ToastUtils，现在已经改名为Toaster了

**Comment by hegaojian** [comment]
在维护的，不过目前没啥计划需要更新的，这种Toastutil更新感觉意义不大，不更新也不会影响什么。不可能专门为了升级它而更新一个版本

**Comment by benxiongbuben** [comment]
好的，谢谢
