### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by booldplx** [hegaojian/MvvmHelper#36]
我使用livedata+databind+viewmodel，之前viewmodel中的数据变化，但是view不会更新。后来发现activity中没有加mBind.viewModel = mViewModel这句关联起来的，我想请问一下，这个代码我试了加不到基类里面（基类里面的mBind没有.viewModel这个属性），那么每个activity或者fragment都必须写一遍了，请问大佬有什么好办法吗？，谢谢

**Comment by hegaojian** [comment]
不好意思现在才看到这个issues，我觉得可以尝试用反射的方式实现吧。你可以先定义一个自己的基类，继承 项目里面的基类，然后在initView方法中，通过反射的方式得到mBind的 viewModel 变量，然后给他赋值，注意记得 要 try catch
