### ISSUE TITLE
越来越ai你了,不砍你

### ISSUE THREAD

**Issue by BaiMingxu1** [hegaojian/MvvmHelper#4]
两个问题
1.为什么放弃navigation
2.dialog封装一下

**Comment by hegaojian** [comment]
复杂的页面跳转逻辑不好处理，没有Activity栈灵活
使用官方的Navigation，每次返回界面会重新创建
使用魔改的Navigation，跳转到另外一个平级界面时，onResume不会触发 只能走onHideChange方法，若用ViewPager包装 则都不会走
界面跳转太快，获取数据和界面UI绘制同时进行会卡顿
全部用navigation不好组件化等等

**Comment by hegaojian** [comment]
你这个dialog封装一下是什么意思

**Comment by yangxiaoge** [comment]
> 复杂的页面跳转逻辑不好处理，没有Activity栈灵活
> 使用官方的Navigation，每次返回界面会重新创建
> 使用魔改的Navigation，跳转到另外一个平级界面时，onResume不会触发 只能走onHideChange方法，若用ViewPager包装 则都不会走
> 界面跳转太快，获取数据和界面UI绘制同时进行会卡顿
> 全部用navigation不好组件化等等

搭车问下，是JetpackMvvm不香了吗😃，刚在看你的JetpackMvvm框架，然后又发现了这个MvvmHelper，突然不知道学哪个了哈哈，望指点下，谢谢！

**Comment by hegaojian** [comment]
> > 复杂的页面偏置逻辑不好处理，没有活动栈灵活
> > 使用官方的导航，一旦返回界面会重新创建
> > 使用魔改的导航，切换到另一个一个平级界面时，onResume不会触发只能走onHideChange方法，若用ViewPager包装则都不会走
> > 界面对齐太快，获取数据和界面UI进行同时进行会卡顿
> > 全部用navigation不好组件化等等
> 
> 搭车问下，是JetpackMvvm不香了吗😃，刚在看你的JetpackMvvm框架，然后又发现了这个MvvmHelper，突然不知道学哪个了哈哈，望指点下，谢谢！

JetpackMvvm应对一般的项目还是蛮香的，只是我不太喜欢用Navigation，里面有些坑，所以新写了一个去除Navigation的MvvmHelper，这个新写的封装比较完善，如果要使用到实际开发中的话，我推荐MvvmHelper，使用起来比JetpackMvvm更舒服

**Comment by yangxiaoge** [comment]
> JetpackMvvm应对一般的项目还是蛮香的，只是我不太喜欢用Navigation，里面有些坑，所以新写了一个去除Navigation的MvvmHelper，这个新写的封装比较完善，如果要使用到实际开发中的话，我推荐MvvmHelper，使用起来比JetpackMvvm更舒服

多谢解答！😃

**Comment by BaiMingxu1** [comment]
感谢我老哥的解答，越来越ai你了。你就是我心里最靓的仔。
