### ISSUE TITLE
鸡哥，首页的标题栏高度会偶现变高

### ISSUE THREAD

**Issue by AndyYw** [hegaojian/MvvmHelper#45]
![lQDPKdG3Jj8XZDfNEgDNDYCw0V1VEynNZQkGnJOTa5SWAA_3456_4608](https://github.com/user-attachments/assets/22393ec8-8d78-4cff-9493-a6085c990d29)

**Comment by hegaojian** [comment]
你是什么手机型号，运行demo直接变成这样了嘛

**Comment by AndyYw** [comment]
我手机里装了一个保活的app，会自动启动。然后在打开这个demo就这样了。一开始运行是好的。 放到下面就好了qaq
 if (paddingTop >= statusBarHeight) return
            layoutParams?.takeIf { it.height > 0 }?.let {
                it.height += statusBarHeight
            }
