### ISSUE TITLE
鸡哥，这个框架怎么在没有持有viewModel的地方调用接口?

### ISSUE THREAD

**Issue by AndyYw** [hegaojian/MvvmHelper#49]
在没有持有viewModel的地方想要调用接口有没有好的方法。比如我现在工具类想调用接口，拿到接口结果直接在这个类处理，这样逻辑都在这个类里。如果通过回调或者LiveDataEvent发出去到activity里面，逻辑比较分散，而且有的逻辑和页面并无关系。

**Comment by hegaojian** [comment]
你可以直接在类里面调用请求方法，比如 val result = Rxhttp.get(xxxx).**toResponse<XXX>**.**tryAwait()** ，拿到结果值为null 就是失败，不为null 就是成功
如果想要请求带弹窗可以自己控制，拿到currentActivity做showLoading 或者  请求结束后 dismiss 

代码示例：
```
scope{
val result = Rxhttp.get(xxxx).toResponse<XXX>.tryAwait()
//TODO
}
```

**Comment by AndyYw** [comment]
好的 谢谢
