### ISSUE TITLE
如果DataBinding的xml中有自定义的布局会有空指针

### ISSUE THREAD

**Issue by LnLooFa** [hegaojian/MvvmHelper#5]
如果DataBinding的xml中有自定义的布局会有空指针
android.content.res.Resources android.content.Context.getResources()

**Comment by hegaojian** [comment]
可以看下你的自定义布局是怎么写的吗，我刚测试了一下在布局中了用了自定义view,并没有提示这个错误啊

**Comment by LnLooFa** [comment]
打扰了,是我自定义View的问题,我改了一下,现在没问题了,改了好久才发现问题..

**Comment by hegaojian** [comment]
可能是你的构造方法没写对，没有传入AttributeSet参数的构造
