### ISSUE TITLE
这个框架和JetPackMvvm应该怎么选择呢?

### ISSUE THREAD

**Issue by zhengjiong** [hegaojian/MvvmHelper#7]
主要区别是什么呢

**Comment by hegaojian** [comment]
都可以用，
1.jetpackmvvm提供了远程依赖的方式，mvvmhelper没有提供，需要将module导入并修改
2.jetpackMvvm有navigation库可以选择使用，mvvmHelper没有提供navigation组件库
3.jetpackMvvm网络框架使用retrofit，mvvmHelper使用第三方网络请求库 rxHttp
4.jetpackMvvm封装层次比较浅，相当于只封装了网络的一些东西，mvvmhelper封装的东西多一点，请求loading有多种方式，可以与界面绑定，分页列表请求等等，拓展性可能更高
